"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from enum import Enum
from typing import Optional

class MoveParameterMove(str, Enum):
    HUMAN = 'human'
    RANDOM = 'random'
    MINIMAX = 'minimax'



@dataclasses.dataclass
class MoveParameter:
    cell_index: Optional[int] = dataclasses.field(default=None)
    move: Optional[MoveParameterMove] = dataclasses.field(default=None)
    

